// nao podemos criar variáveis com palavras reservadas
// variáveis precisam ter nomes significativos
// nao pode começar o nome de uma variável com um numero
// nao podem conter espaços ou traços
// utilizamos camelCase(letras maiúsculas a partir da segunda palavra)
// Case-sensitive(letras maiúsculas e minúsculas sao variáveis diferentes)
// nao podemos recriar variável com let
// nao utiliza var, utilize let sempre
let nome = 'amigao';
console.log(nome)
//testando se aprendo a usar o git